/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthUsersImport } from './routes/_auth/users'
import { Route as AuthUsersIndexImport } from './routes/_auth/users/index'
import { Route as AuthUsersCreateImport } from './routes/_auth/users/create'
import { Route as AuthUsersUserIdImport } from './routes/_auth/users/$userId'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthUsersRoute = AuthUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)

const AuthUsersIndexRoute = AuthUsersIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthUsersRoute,
} as any)

const AuthUsersCreateRoute = AuthUsersCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthUsersRoute,
} as any)

const AuthUsersUserIdRoute = AuthUsersUserIdImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AuthUsersRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users/$userId': {
      id: '/_auth/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthUsersUserIdImport
      parentRoute: typeof AuthUsersImport
    }
    '/_auth/users/create': {
      id: '/_auth/users/create'
      path: '/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthUsersCreateImport
      parentRoute: typeof AuthUsersImport
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexImport
      parentRoute: typeof AuthUsersImport
    }
  }
}

// Create and export the route tree

interface AuthUsersRouteChildren {
  AuthUsersUserIdRoute: typeof AuthUsersUserIdRoute
  AuthUsersCreateRoute: typeof AuthUsersCreateRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthUsersRouteChildren: AuthUsersRouteChildren = {
  AuthUsersUserIdRoute: AuthUsersUserIdRoute,
  AuthUsersCreateRoute: AuthUsersCreateRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthUsersRouteWithChildren = AuthUsersRoute._addFileChildren(
  AuthUsersRouteChildren,
)

interface AuthRouteChildren {
  AuthUsersRoute: typeof AuthUsersRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUsersRoute: AuthUsersRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/users': typeof AuthUsersRouteWithChildren
  '/': typeof AuthIndexRoute
  '/users/$userId': typeof AuthUsersUserIdRoute
  '/users/create': typeof AuthUsersCreateRoute
  '/users/': typeof AuthUsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/users/$userId': typeof AuthUsersUserIdRoute
  '/users/create': typeof AuthUsersCreateRoute
  '/users': typeof AuthUsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/users': typeof AuthUsersRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/users/$userId': typeof AuthUsersUserIdRoute
  '/_auth/users/create': typeof AuthUsersCreateRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/users'
    | '/'
    | '/users/$userId'
    | '/users/create'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users/$userId' | '/users/create' | '/users'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/users'
    | '/_auth/'
    | '/_auth/users/$userId'
    | '/_auth/users/create'
    | '/_auth/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/users",
        "/_auth/"
      ]
    },
    "/_auth/users": {
      "filePath": "_auth/users.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/users/$userId",
        "/_auth/users/create",
        "/_auth/users/"
      ]
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/users/$userId": {
      "filePath": "_auth/users/$userId.tsx",
      "parent": "/_auth/users"
    },
    "/_auth/users/create": {
      "filePath": "_auth/users/create.tsx",
      "parent": "/_auth/users"
    },
    "/_auth/users/": {
      "filePath": "_auth/users/index.tsx",
      "parent": "/_auth/users"
    }
  }
}
ROUTE_MANIFEST_END */
